### PR TITLE
updates for deployment 2021-1.0

### PR DESCRIPTION
**Pull request by jklynch**
Updates borrowed from SRX deployment.

### CODE REVIEW

**Comment by mrakitin** [comment]
[CI test](https://dev.azure.com/nsls2/profile_collections/_build/results?buildId=1351&view=logs&j=c58b40dd-1ba0-5a8c-8e7a-987c20afdefa&t=8f1b40f4-c2fc-5e37-c197-a69f5d504b9f) is successful now.

**Comment by mrakitin** [comment]
@jklynch, @bsobhani, I think it's ready to go. I just reran the tests with the `collection-2021-1.0` and `collection-2021-1.2` conda envs, and they passed. Even if ESM still prefers to stay on the 2021-2.0rc7 environment, we should get most of the changes in.

Alex, do you mind testing `bsui` with the `collection-2021-1.0` or newer on the beamline and let us know if it resolved the slowness with updating PVs in your GUI?

**Comment by bsobhani** [comment]
I just tried opening bsui with this branch and I get "AttributeError: type object 'EpicsSignalBase' has no attribute 'set_defaults'", I will check with the beamline to see when they want to start testing the new environment. For the ophyd problems for reading images - I found a possible workaround which I am awaiting Elio's input on.

**Comment by mrakitin** [comment]
> I just tried opening bsui with this branch and I get "AttributeError: type object 'EpicsSignalBase' has no attribute 'set_defaults'", I will check with the beamline to see when they want to start testing the new environment. For the ophyd problems for reading images - I found a possible workaround which I am awaiting Elio's input on.

Thanks for the test, @bsobhani! The way to test it would be to use this command:
```bash
BS_ENV=collection-2021-1.2 bsui
```

I believe the newer versions of the collection environment have the `set_defaults` method, as it's successfully passing here.

This PR has a lot of useful updates (such as parametrization of the profile's `startup` dir location, so it can be ported, or renamed without the need to update the paths to the files in the code). Maybe I should split this PR into two or more. Thoughts?

**Pull request merged**
